=== cbmira01/TOPS-10-Build/Drifter/media/decus10-manifest.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="decusProjects">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="decusProject">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="decusNumber" type="xs:string" />
              <xs:element name="projectProgrammerNumber" type="xs:string" />
              <xs:element name="projectName" type="xs:string" />
              <xs:element name="description" type="xs:string" />
              <xs:element name="decusTapeName" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cbmira01/TOPS-10-Build/Drifter/media/decus10-manifest.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
    DECUS Program Library for DECsystem-10/20

    Some of this information was gathered from the 
        DECUS Program Library DECsystem-10/20 Catalog of April 1978:
        https://ia801902.us.archive.org/4/items/bitsavers_decdecuspratalogPDP10Apr78_4405080/DECUS_Catalog_PDP-10_Apr78.pdf

    Other details were discovered by inspection of the tape contents.
-->

<decusProjects
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="decus10-manifest.xsd">
  <decusProject id="0235c7dd-e679-49e6-9872-55dbb11aeaba">
    <decusNumber>10-3</decusNumber>
    <projectProgrammerNumber>[43,50003]</projectProgrammerNumber>
    <projectName>DTLOTS: Lots of Copies of a DECtape</projectName>
    <description>DECtape manipulation</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="fa2f7092-6b8a-4c88-8724-a710ca5c653f">
    <decusNumber>10-8</decusNumber>
    <projectProgrammerNumber>[43,50010]</projectProgrammerNumber>
    <projectName>DECtape DDT</projectName>
    <description>DECtape manipulation</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="70f8c4f9-043f-4867-a354-62530bdd1e7e">
    <decusNumber>10-9</decusNumber>
    <projectProgrammerNumber>[43,50011]</projectProgrammerNumber>
    <projectName>Music System for the PDP-10</projectName>
    <description>music player and music files</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="975d03bb-e021-433d-ade2-ea1644a9cdd5">
    <decusNumber>10-10</decusNumber>
    <projectProgrammerNumber>[43,50012]</projectProgrammerNumber>
    <projectName>EIGHT and EDIT8</projectName>
    <description>PDP-8 DECtape conversion</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="e21ab859-83a2-4e70-9c23-96c4e1c6e723">
    <decusNumber>10-12</decusNumber>
    <projectProgrammerNumber>[43,50014]</projectProgrammerNumber>
    <projectName>PAL10</projectName>
    <description>cross-assembler for PDP-8</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="d3249278-16d4-493a-84c6-de4d6e249fae">
    <decusNumber>10-22</decusNumber>
    <projectProgrammerNumber>[43,50026]</projectProgrammerNumber>
    <projectName>JACOBI</projectName>
    <description>matrix diagonalization, in Macro-10</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="0e5f5cbe-c24d-4ff5-b657-af1fcd03f92c">
    <decusNumber>10-23</decusNumber>
    <projectProgrammerNumber>[43,50027]</projectProgrammerNumber>
    <projectName>SPEEDY</projectName>
    <description>source possibly mangled ?</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="deaa08ec-877b-4b20-af60-fa1958efe9e4">
    <decusNumber>10-25</decusNumber>
    <projectProgrammerNumber>[43,50031]</projectProgrammerNumber>
    <projectName>ONCE</projectName>
    <description>FORTRAN subroutine debugger </description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="b8430edf-7653-4ba6-acd1-d35b0957950b">
    <decusNumber>10-27</decusNumber>
    <projectProgrammerNumber>[43,50033]</projectProgrammerNumber>
    <projectName>GASP II</projectName>
    <description>FORTRAN subroutine for discrete simulation studies</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="d278219c-3e3b-425b-beaf-29a8d25c1a50">
    <decusNumber>10-28</decusNumber>
    <projectProgrammerNumber>[43,50034]</projectProgrammerNumber>
    <projectName>SIM-11</projectName>
    <description>PDP-11 simulator program</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="ba083e38-1661-4073-ab7f-d328cb5a47de">
    <decusNumber>10-29</decusNumber>
    <projectProgrammerNumber>[43,50035]</projectProgrammerNumber>
    <projectName>MUNICH</projectName>
    <description>Munich real-time data acquisition system</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="f6635556-821a-42ce-af0f-7a44892d74c9">
    <decusNumber>10-30</decusNumber>
    <projectProgrammerNumber>[43,50036]</projectProgrammerNumber>
    <projectName>NVERTX</projectName>
    <description>FORTRAN subroutines for high-energy physics</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="a491a8fb-fae0-49e2-a09e-4d71504e8e33">
    <decusNumber>10-31</decusNumber>
    <projectProgrammerNumber>[43,50037]</projectProgrammerNumber>
    <projectName>PALX11</projectName>
    <description>cross-assembler for PDP-8?</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="cceccd80-0714-4f37-b150-592556c01065">
    <decusNumber>10-33</decusNumber>
    <projectProgrammerNumber>[43,50041]</projectProgrammerNumber>
    <projectName>W</projectName>
    <description>error function for complex argument, in FORTRAN</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="52558ddc-ea97-4eee-ad2f-82196fdf6120">
    <decusNumber>10-36</decusNumber>
    <projectProgrammerNumber>[43,50044]</projectProgrammerNumber>
    <projectName>ARP</projectName>
    <description>utility routines for character, byte, and logic operations</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="4a9226bc-e038-4bfa-866b-e28b1743f7b8">
    <decusNumber>10-37</decusNumber>
    <projectProgrammerNumber>[43,50045]</projectProgrammerNumber>
    <projectName>Trace Program</projectName>
    <description>batch-oriented debugging</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="eb1ae18a-007e-4575-bcad-43b22decb389">
    <decusNumber>10-38</decusNumber>
    <projectProgrammerNumber>[43,50046]</projectProgrammerNumber>
    <projectName>CHARTR</projectName>
    <description>produces FORTRAN flow charts</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="02d0b069-dade-4681-9590-0d1b9ab2794c">
    <decusNumber>10-43</decusNumber>
    <projectProgrammerNumber>[43,50053]</projectProgrammerNumber>
    <projectName>Random Number Package</projectName>
    <description>various numerical routines, in Macro-10 </description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="563d3a38-3971-418c-b305-d4845a054cab">
    <decusNumber>10-57</decusNumber>
    <projectProgrammerNumber>[43,50071]</projectProgrammerNumber>
    <projectName>SIMPLE</projectName>
    <description>simulation routine, in FORTRAN</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="a83013ab-3bfb-4039-9cd1-b1ce94131f4b">
    <decusNumber>10-59</decusNumber>
    <projectProgrammerNumber>[43,50073]</projectProgrammerNumber>
    <projectName>LISP 1.6</projectName>
    <description>programming language</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="2f8c9c1c-7f7b-4a78-b7f7-4aebe68e8c94">
    <decusNumber>10-61</decusNumber>
    <projectProgrammerNumber>[43,50075]</projectProgrammerNumber>
    <projectName>MLISP</projectName>
    <description>programming language; compiler</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="ac8ab8b0-0b57-43c4-9c6b-92a8021d4c56">
    <decusNumber>10-65</decusNumber>
    <projectProgrammerNumber>[43,50101]</projectProgrammerNumber>
    <projectName>LEARNS</projectName>
    <description>subroutines that are used often</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="fa8929d2-b53f-48f1-b3cf-8f71ab3335d9">
    <decusNumber>10-68</decusNumber>
    <projectProgrammerNumber>[43,50104]</projectProgrammerNumber>
    <projectName>PAL12</projectName>
    <description>cross-assembler for PDP-8</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="ee91fd9a-004d-4ad2-9362-dc2c55518252">
    <decusNumber>10-70</decusNumber>
    <projectProgrammerNumber>[43,50106]</projectProgrammerNumber>
    <projectName>FAKE</projectName>
    <description>fake dynamic array assignments for FORTRAN</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="a81cd96b-4aab-4c82-89a7-0247418dea61">
    <decusNumber>10-72</decusNumber>
    <projectProgrammerNumber>[43,50110]</projectProgrammerNumber>
    <projectName>Dartmouth BASIC Library</projectName>
    <description>game, numerical, and financial programs, in BASIC</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="da97cfc2-5e26-4eb9-8e8a-1e935ebe6d26">
    <decusNumber>none</decusNumber>
    <projectProgrammerNumber>[43,50126]</projectProgrammerNumber>
    <projectName>none</projectName>
    <description>possibly an incomplete dump of someone's SYS area ?</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="a5c92e1d-4394-42ff-9aca-d93222d6d773">
    <decusNumber>10-87</decusNumber>
    <projectProgrammerNumber>[43,50127]</projectProgrammerNumber>
    <projectName>MATRIX</projectName>
    <description>matrix interpretive program</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject id="6503e4ed-21d5-4cb6-84ef-fe5c4a93ef33">
    <decusNumber>10-88</decusNumber>
    <projectProgrammerNumber>[43,50130]</projectProgrammerNumber>
    <projectName>SALESM</projectName>
    <description>sales commission calculator, in BASIC</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
