=== cbmira01/TOPS-10-Build/Drifter/media/tops10-tape-manifest.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tapes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="tape">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="label" type="xs:string" />
              <xs:element name="name" type="xs:string" />
              <xs:element name="notes" type="xs:string" />
              <xs:element name="purpose" type="xs:string" />
              <xs:element name="filename" type="xs:string" />
              <xs:element name="urls">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="url">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="preferred" type="xs:boolean" use="optional" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cbmira01/TOPS-10-Build/Drifter/media/tops10-tape-manifest.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- http://pdp-10.trailing-edge.com/ -->
<!-- http://www.textfiles.com/bitsavers/bits/DEC/pdp10/magtape/dec_distribs/labels.txt -->

<tapes
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tops10-tape-manifest.xsd">

    <!-- TOPS-10 7.04 Monitor Installation -->

    <tape id="649648dd-af8c-4653-93c1-88dbf1825b25">
        <label>BB-X138C-BB</label>
        <name>TOPS-10 7.04 KS Bootable tape</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>ks_bootable.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/tops10_ks_bootable_bb-x138c-bb_704.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/tops10_ks_bootable_bb-x138c-bb_704.tap.bz2</url>
            <url>http://www.bitsavers.org/bits/DEC/pdp10/magtape/dec_distribs/TOPS-10/BB-X138C-BB_1988.tap.gz</url>
        </urls>
    </tape>
    <tape id="46683e17-c0fe-4d43-b0cf-d068ef1d5078">
        <label>BB-X140C-SB</label>
        <name>TOPS-10 7.04 Montor ANF</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>monitor_anf.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/tops10_704_monitoranf_bb-x140c-sb.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/tops10_704_monitoranf_bb-x140c-sb.tap.bz2</url>
            <url>https://github.com/PDP-10/tops10-tapes/raw/576b4bdfb4f05da3d1de235a111aba9b30e0606d/mandatory/tops10_704_monitoranf_bb-x140c-sb.tap</url>
        </urls>
    </tape>
    <tape id="52d8bd4a-a25a-429f-b2f3-8ca1fac6e0af">
        <label>BB-X133C-SB</label>
        <name>TOPS-10 7.04 MPE</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>mpe.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/tops10v704_mpe.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/tops10v704_mpe.tap.bz2</url>
            <url>http://www.bitsavers.org/bits/DEC/pdp10/magtape/dec_distribs/TOPS-10/BB-X133C-SB_1988.tap.gz</url>
        </urls>
    </tape>
    <tape id="3a117bb6-576a-41ce-8e13-8e1783591f2f">
        <label>no label</label>
        <name>TOPS-10 7.04 SPI Monitor</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>spi_monitor.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/tops-10_7_04_spi_monitor.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/tops-10_7_04_spi_monitor.tap.bz2</url>
        </urls>
    </tape>
    <tape id="34ffdec1-2f94-4c74-9444-88e957827ce1">
        <label>BB-X128C-SB</label>
        <name>TOPS-10 CUSP BIN and SRC, tape 1 of 2</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>cusp_1of2.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/cuspbinsrc_1of2_bb-x128c-sb.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/cuspbinsrc_1of2_bb-x128c-sb.tap.bz2</url>
            <url>https://github.com/PDP-10/tops10-tapes/raw/576b4bdfb4f05da3d1de235a111aba9b30e0606d/mandatory/cuspbinsrc_1of2_bb-x128c-sb.tap</url>
        </urls>
    </tape>
    <tape id="d4825a77-a366-4513-ae78-ad11acc3f509">
        <label>BB-FP63B-SB</label>
        <name>TOPS-10 CUSP BIN and SRC, tape 2 of 2</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>cusp_2of2.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/cuspbinsrc_2of2_bb-fp63b-sb.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/cuspbinsrc_2of2_bb-fp63b-sb.tap.bz2</url>
            <url>https://github.com/PDP-10/tops10-tapes/raw/576b4bdfb4f05da3d1de235a111aba9b30e0606d/mandatory/cuspbinsrc_2of2_bb-fp63b-sb.tap</url>
        </urls>
    </tape>
    <tape id="585b6894-1ca9-4749-95be-b4198b39963a">
        <label>BB-X130C-SB</label>
        <name>TOPS-10 Customer Supported CUSPs</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>customer_cusps.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/cust_sup_cusp_bb-x130c-sb.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/cust_sup_cusp_bb-x130c-sb.tap.bz2</url>
            <url>https://github.com/PDP-10/tops10-tapes/raw/576b4bdfb4f05da3d1de235a111aba9b30e0606d/mandatory/cust_sup_cusp_bb-x130c-sb.tap</url>
        </urls>
    </tape>
    <tape id="71263c87-4c9a-4354-a8a2-ba96453ec194">
        <label>BB-FP64B-SB</label>
        <name>TOPS-10 Tools</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>tools.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/tops10_tools_bb-fp64b-sb.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/tops10_tools_bb-fp64b-sb.tap.bz2</url>
            <url>https://github.com/PDP-10/tops10-tapes/raw/576b4bdfb4f05da3d1de235a111aba9b30e0606d/tools/tops10_tools_bb-fp64b-sb.tap</url>
        </urls>
    </tape>
    <tape id="60fc1557-c2e0-4a1a-a86d-d2bc7773f130">
        <label>no label</label>
        <name>TOPS-10 V7.04 Auxilluary Tape for TOPS-10 V7.04 Load 361</name>
        <notes></notes>
        <purpose>TOPS-10 7.04 Monitor Installation</purpose>
        <filename>auxilluary.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/tops10v704_auxft.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/tops10v704_auxft.tap.bz2</url>
        </urls>
    </tape>

    <!-- TOPS-10 Layered Products -->

    <tape id="d4becb5c-0795-4648-9f3e-5982c9bf229f">
        <label>AP-5069B-SB</label>
        <name>ALGOL-10 Version 10 1977</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>algol_10.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/ap-5069b-sb.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/ap-5069b-sb.tap.bz2</url>
        </urls>
    </tape>
    <tape id="422dbc35-29f9-4ba6-b5d4-b8e7581e8130">
        <label>AP-5069C-SB</label>
        <name>ALGOL-10 Version 10A 1978</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>algol_10a.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/ap-5069c-sb.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/ap-5069c-sb.tap.bz2</url>
        </urls>
    </tape>
    <tape id="dca9e0f2-5aff-4a48-a76f-eced75fbf586">
        <label>no label</label>
        <name>APLSF V2 (435) September 1979</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>aplsf_v2.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/aplsfv2.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/aplsfv2.tap.bz2</url>
        </urls>
    </tape>
    <tape id="5d5f65c2-f37c-4567-880d-d8e4813827f9">
        <label>BB-M178A-SB</label>
        <name>BASIC-10 V17F 18-May-1981</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>basic-10_v17f.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/basic17f.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/basic17f.tap.bz2</url>
        </urls>
    </tape>
    <tape id="de697eb7-c797-48d5-8b28-e8d8f7d058b3">
        <label>BB-J941F-BB</label>
        <name>BLISS-36 V4.2 (236) 16-Oct-1989</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>bliss-36_v42.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/bls36v42.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/bls36v42.tap.bz2</url>
        </urls>
    </tape>
    <tape id="278479f1-914a-4a40-a343-baadf58f7cd2">
        <label>AP-C800D-SB</label>
        <name>DEC 10 COBOL 68 V12A APR 16 1980</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>cobol-68_v12a.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/ap-c800d-sb.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/ap-c800d-sb.tap.bz2</url>
        </urls>
    </tape>
    <tape id="50fbd1bb-6fd1-472d-b4d7-9d9cebcc9b82">
        <label>no label</label>
        <name>COBOL-74 V12C</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>cobol-74_v12c.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/cobol12c.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/cobol12c.tap.bz2</url>
        </urls>
    </tape>
    <tape id="a14d3899-d57a-4ca5-b3b4-fe023b3ee433">
        <label>no label</label>
        <name>DBMS V5A</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>dbms_v5a.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/dbmsv5a.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/dbmsv5a.tap.bz2</url>
        </urls>
    </tape>
    <tape id="f577e8e9-ed3e-4951-a28d-0ca12b1d2a99">
        <label>no label</label>
        <name>IQL3A V30 21-Feb-1980</name>
        <notes></notes>
        <purpose>TOPS-10 Layered Products</purpose>
        <filename>iql3a_v30.tape</filename>
        <urls>
            <url preferred="true">http://localhost/tapes/iqlv30.tap</url>
            <url>http://pdp-10.trailing-edge.com/tapes/iqlv30.tap.bz2</url>
        </urls>
    </tape>
    <tape id="71d680f5-760d-44a6-ac05-89f7014b93fb">
