=== cbmira01/TOPS-10-Build/manifests/decus10-manifest.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Schema generation thanks to https://www.freeformatter.com/  -->

<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    attributeFormDefault="unqualified" 
    elementFormDefault="qualified">
  <xs:element name="decusProjects">
    <xs:annotation>
      <xs:documentation>Some of this information was gathered from the 
        DECUS Program Library DECsystem-10/20 Catalog of April 1978:
        https://ia801902.us.archive.org/4/items/bitsavers_decdecuspratalogPDP10Apr78_4405080/DECUS_Catalog_PDP-10_Apr78.pdf

    Other details were discovered by inspection.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="decusProject" maxOccurs="unbounded" minOccurs="0">
          <xs:annotation>
            <xs:documentation>DECUS Program Library DECsystem-10/20 Catalog of April 1978 ends at this point...</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="decusNumber"/>
              <xs:element type="xs:string" name="projectProgrammerNumber"/>
              <xs:element type="xs:string" name="projectName"/>
              <xs:element type="xs:string" name="description"/>
              <xs:element type="xs:string" name="decusTapeName"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cbmira01/TOPS-10-Build/manifests/decus10-manifest.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
    Some of this information was gathered from the 
        DECUS Program Library DECsystem-10/20 Catalog of April 1978:
        https://ia801902.us.archive.org/4/items/bitsavers_decdecuspratalogPDP10Apr78_4405080/DECUS_Catalog_PDP-10_Apr78.pdf

    Other details were discovered by inspection.
-->

<decusProjects
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="decus10-manifest.xsd">
  <decusProject>
    <decusNumber>10-3</decusNumber>
    <projectProgrammerNumber>[43,50003]</projectProgrammerNumber>
    <projectName>DTLOTS: Lots of Copies of a DECtape</projectName>
    <description>DECtape manipulation</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-8</decusNumber>
    <projectProgrammerNumber>[43,50010]</projectProgrammerNumber>
    <projectName>DECtape DDT</projectName>
    <description>DECtape manipulation</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-9</decusNumber>
    <projectProgrammerNumber>[43,50011]</projectProgrammerNumber>
    <projectName>Music System for the PDP-10</projectName>
    <description>music player and music files</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-10</decusNumber>
    <projectProgrammerNumber>[43,50012]</projectProgrammerNumber>
    <projectName>EIGHT and EDIT8</projectName>
    <description>PDP-8 DECtape conversion</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-12</decusNumber>
    <projectProgrammerNumber>[43,50014]</projectProgrammerNumber>
    <projectName>PAL10</projectName>
    <description>cross-assembler for PDP-8</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-22</decusNumber>
    <projectProgrammerNumber>[43,50026]</projectProgrammerNumber>
    <projectName>JACOBI</projectName>
    <description>matrix diagonalization, in Macro-10</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-23</decusNumber>
    <projectProgrammerNumber>[43,50027]</projectProgrammerNumber>
    <projectName>SPEEDY</projectName>
    <description>source possibly mangled ?</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-25</decusNumber>
    <projectProgrammerNumber>[43,50031]</projectProgrammerNumber>
    <projectName>ONCE</projectName>
    <description>FORTRAN subroutine debugger </description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-27</decusNumber>
    <projectProgrammerNumber>[43,50033]</projectProgrammerNumber>
    <projectName>GASP II</projectName>
    <description>FORTRAN subroutine for discrete simulation studies</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-28</decusNumber>
    <projectProgrammerNumber>[43,50034]</projectProgrammerNumber>
    <projectName>SIM-11</projectName>
    <description>PDP-11 simulator program</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-29</decusNumber>
    <projectProgrammerNumber>[43,50035]</projectProgrammerNumber>
    <projectName>MUNICH</projectName>
    <description>Munich real-time data acquisition system</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-30</decusNumber>
    <projectProgrammerNumber>[43,50036]</projectProgrammerNumber>
    <projectName>NVERTX</projectName>
    <description>FORTRAN subroutines for high-energy physics</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-31</decusNumber>
    <projectProgrammerNumber>[43,50037]</projectProgrammerNumber>
    <projectName>PALX11</projectName>
    <description>cross-assembler for PDP-8?</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-33</decusNumber>
    <projectProgrammerNumber>[43,50041]</projectProgrammerNumber>
    <projectName>W</projectName>
    <description>error function for complex argument, in FORTRAN</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-36</decusNumber>
    <projectProgrammerNumber>[43,50044]</projectProgrammerNumber>
    <projectName>ARP</projectName>
    <description>utility routines for character, byte, and logic operations</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-37</decusNumber>
    <projectProgrammerNumber>[43,50045]</projectProgrammerNumber>
    <projectName>Trace Program</projectName>
    <description>batch-oriented debugging</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-38</decusNumber>
    <projectProgrammerNumber>[43,50046]</projectProgrammerNumber>
    <projectName>CHARTR</projectName>
    <description>produces FORTRAN flow charts</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-43</decusNumber>
    <projectProgrammerNumber>[43,50053]</projectProgrammerNumber>
    <projectName>Random Number Package</projectName>
    <description>various numerical routines, in Macro-10 </description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-57</decusNumber>
    <projectProgrammerNumber>[43,50071]</projectProgrammerNumber>
    <projectName>SIMPLE</projectName>
    <description>simulation routine, in FORTRAN</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-59</decusNumber>
    <projectProgrammerNumber>[43,50073]</projectProgrammerNumber>
    <projectName>LISP 1.6</projectName>
    <description>programming language</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-61</decusNumber>
    <projectProgrammerNumber>[43,50075]</projectProgrammerNumber>
    <projectName>MLISP</projectName>
    <description>programming language; compiler</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-65</decusNumber>
    <projectProgrammerNumber>[43,50101]</projectProgrammerNumber>
    <projectName>LEARNS</projectName>
    <description>subroutines that are used often</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-68</decusNumber>
    <projectProgrammerNumber>[43,50104]</projectProgrammerNumber>
    <projectName>PAL12</projectName>
    <description>cross-assembler for PDP-8</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-70</decusNumber>
    <projectProgrammerNumber>[43,50106]</projectProgrammerNumber>
    <projectName>FAKE</projectName>
    <description>fake dynamic array assignments for FORTRAN</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-72</decusNumber>
    <projectProgrammerNumber>[43,50110]</projectProgrammerNumber>
    <projectName>Dartmouth BASIC Library</projectName>
    <description>game, numerical, and financial programs, in BASIC</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>none</decusNumber>
    <projectProgrammerNumber>[43,50126]</projectProgrammerNumber>
    <projectName>none</projectName>
    <description>possibly an incomplete dump of someone's SYS area ?</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-87</decusNumber>
    <projectProgrammerNumber>[43,50127]</projectProgrammerNumber>
    <projectName>MATRIX</projectName>
    <description>matrix interpretive program</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-88</decusNumber>
    <projectProgrammerNumber>[43,50130]</projectProgrammerNumber>
    <projectName>SALESM</projectName>
    <description>sales commission calculator, in BASIC</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-89</decusNumber>
    <projectProgrammerNumber>[43,50131]</projectProgrammerNumber>
    <projectName>JOTTO</projectName>
    <description>game, in FORTRAN</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-90</decusNumber>
    <projectProgrammerNumber>[43,50132]</projectProgrammerNumber>
    <projectName>BARTEE</projectName>
    <description>minimization of logic networks, in Macro-10</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-93
        </decusNumber>
    <projectProgrammerNumber>[43,50135]</projectProgrammerNumber>
    <projectName>BCDPIP</projectName>
    <description>translates IBM 7040 mag tapes to ASCII format</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-97</decusNumber>
    <projectProgrammerNumber>[43,50141]</projectProgrammerNumber>
    <projectName>TUTR</projectName>
    <description>timesharing tutorial programs, in BASIC</description>
    <decusTapeName>DECUS 10-LIB-1</decusTapeName>
  </decusProject>
  <decusProject>
    <decusNumber>10-98</decusNumber>
